Repository blockcoders/harmony-marketplace-sdk, pull requests merged in 2022-02, with the labels that each got.

#18 Feature/baseHRC1155
  package-lock.json
  package.json
  src/base-hrc721.ts
  src/base-token.ts
  src/hrc1155.ts
  src/hrc721.spec.ts
  src/hrc721.ts
Labels: feature

#23 feature/bignumberish
  src/base-token.ts
  src/hrc1155.spec.ts
  src/hrc1155.ts
  src/hrc721.spec.ts
  src/hrc721.ts
  src/tests/constants.ts
Labels: feature

#26 Feature/base token tests 164
  src/base-token.spec.ts
  src/base-token.ts
  src/tests/constants.ts
Labels: feature

#29 New interfaces
  package-lock.json
  package.json
  src/_version.ts
  src/base-token.spec.ts
  src/base-token.ts
  src/constants.ts
  src/hrc1155.spec.ts
  src/hrc1155.ts
  src/hrc721.spec.ts
  src/hrc721.ts
  src/index.ts
  src/interfaces.ts
  src/key.ts
  src/logger.ts
  src/mnemonic-key.ts
  src/networks.ts
  src/private-key.ts
  src/tests/constants.ts
  src/tests/contracts/HR1155/abi.ts
  src/tests/contracts/HR721/abi.ts
  src/utils.ts
  tsconfig.json
Labels: bug, enhancement

#31 Update README
  README.md
  package-lock.json
  package.json
  src/base-token.spec.ts
  src/base-token.ts
  src/constants.ts
  src/hrc1155.spec.ts
  src/hrc721.spec.ts
  src/interfaces.ts
  src/mnemonic-key.ts
  src/tests/contracts/HRC1155/abi.ts
  src/tests/contracts/HRC721/abi.ts
Labels: documentation

#33 circleci
  .circleci/config.yml
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .nycrc
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement

#30 Feature/safeBatch
  src/hrc1155.spec.ts
  src/hrc721.spec.ts
Labels: feature

#35 Feature/testKeyClass
  src/key.spec.ts
Labels: feature

#37 Feature/privateKeyTest
  src/private-key.spec.ts
Labels: enhancement
