Repository blockcoders/harmony-marketplace-sdk, pull requests merged in 2022-10, with the labels that each got.

#61 Added Metamask example to README
  README.md
Labels: documentation

#68 Support for payable contract methods
  src/interfaces.ts
Labels: enhancement

#69 Metamask signing support
  README.md
  src/index.ts
  src/interfaces.ts
  src/providers/index.ts
  src/providers/metamaskProvider.ts
  src/wallets/key.ts
Labels: documentation, enhancement
